### ISSUE TITLE
Location for events on the ./events page

### ISSUE THREAD

**Issue by m-decarli** [heddendorp/section-app-client#527]
Some events - like "language cafe" or "office hours" - have to be specified, where they take place. For now this is done in the title.

A small icon of a campus and "Garching" or "Weihenstephan" or "main campus" could be added, to make it easier to see where the event is taking place.

This should be defined on the edit page by a drop down with "summary location". The selectable values should be defined ba the admin on the global admin page.

Possible categories could be:

- None
- campus Garching
- campus Straubing
- main campus Munich
- campus Weihenstephan
- Garching
- Munich

This would make it easier for participants to immediately see, where this will take place.
The default value is None and this will show nothing on the ./events page, as it is currently the case.

**Comment by ZuzkaU** [comment]
Maybe even add (imprecise) coordinates or at least arbitrary textual description of the place? It is not always clear for participants (and organizers) if they can be on time for the event without knowing where it is before signup, travel through Munich takes time.

**Comment by heddendorp** [comment]
I think the current solutions of description and title are sufficient
