### ISSUE TITLE
Some visual bugs

### ISSUE THREAD

**Issue by m-decarli** [heddendorp/section-app-client#754]
Firefox 112.0.2 (64-bit) on
Windows 10
Full HD screen resolution

### under past events, the ones that haven't been rated yet
![image](https://user-images.githubusercontent.com/113024095/235870318-87834679-38a9-4d5e-842b-dfb75c2bbeea.png)

### rate events
![image](https://user-images.githubusercontent.com/113024095/235870681-930a9012-c67c-4b0d-861d-58aa1f470674.png)
- the textbox could be as wide as the rating tab
- the text for organisers collides with the description of the text box

**Comment by heddendorp** [comment]
The visual issues with ratings have been fixed
