### ISSUE TITLE
User without elevated rights registers for drafted events

### ISSUE THREAD

**Issue by yyywing** [heddendorp/section-app-client#778]
One specific user is able to register to Drafted events, even though he is not a Tutor nor a Trial user.

He himself has no idea what he does differently, he was also able to reproduce it multiple times.

**Comment by heddendorp** [comment]
I would be great to learn more about this user, feel free to send me an email.
Also, is there any way, this user has received the unique url of the event or do they see the event in the normal list?
Please be as explicit as possible to narrow down the issue here.

**Comment by heddendorp** [comment]
This was investigated and seems to not be a reoccurring problem
