### ISSUE TITLE
Event location not visible once registered

### ISSUE THREAD

**Issue by yyywing** [heddendorp/section-app-client#780]
Unable to access the event location once registered for the event.

On multiple occasions we had participants unable to find the location on the event page after registering.

**Comment by heddendorp** [comment]
Hey, thanks for raising this.
It would be great to have some more info such as a link to the event or another way to get more information.
Recently this was an issue with external events. Here users can not register and will never see the location, only the other event types have that feature.

**Comment by heddendorp** [comment]
This seems to have been am misunderstanding about how different kinds of events work
