### ISSUE TITLE
Improve event location field

### ISSUE THREAD

**Issue by jacbz** [heddendorp/section-app-client#89]
- [ ] There should be three different event locations:
- Google Maps API (location + place ID)
- Manual text + manual coordinates
- Online + URL (for Zoom conferences, online chess tournaments, etc.)

The user should be able to select the type of event location by three tabs.

- [x] when entering a place, "Open in Maps" should open the place and not the coordinates
- [x] improve place autocomplete

**Comment by heddendorp** [comment]
The last two are somewhat hard as we rely on the bing maps service here, It's only possible to open the map to the coordinates and not the point of interest as we do not have any poi information that can be used by google maps.
Almost the same issue with the last point, these come directly from bing map(azure maps). The only option here would be to move to and pay for the google maps api. Although it seems like we should be able to stay within the free limits.
